In [ ]:
import pandas as pd

esco_rel = pd.read_csv("/Users/nguyenduykhanh/Documents/GraduationProject/Recommendation_Project/recommendation/dataset/ESCO_taxonomy/esco_keep/occupationSkillRelations_en.csv")

# giữ cột cần thiết
esco_rel = esco_rel[
    [
        "occupationUri",
        "occupationLabel",
        "relationType",
        "skillType",
        "skillUri",
        "skillLabel",
    ]
].copy()

esco_rel.head()

,occupationUri,occupationLabel,relationType,skillType,skillUri,skillLabel
0,http://data.europa.eu/esco/occupation/00030d09...,technical director,essential,knowledge,http://data.europa.eu/esco/skill/fed5b267-73fa...,theatre techniques
1,http://data.europa.eu/esco/occupation/00030d09...,technical director,essential,skill/competence,http://data.europa.eu/esco/skill/05bc7677-5a64...,organise rehearsals
2,http://data.europa.eu/esco/occupation/00030d09...,technical director,essential,skill/competence,http://data.europa.eu/esco/skill/271a36a0-bc7a...,write risk assessment on performing arts produ...
3,http://data.europa.eu/esco/occupation/00030d09...,technical director,essential,skill/competence,http://data.europa.eu/esco/skill/47ed1d37-971b...,coordinate with creative departments
4,http://data.europa.eu/esco/occupation/00030d09...,technical director,essential,skill/competence,http://data.europa.eu/esco/skill/591dd514-735b...,adapt to artists' creative demands

# Tạo bộ từ khóa nghề IT

In [12]:
it_patterns = [
    "ict ",
    "software",
    "web developer",
    "web designer",
    "webmaster",
    "mobile application developer",
    "cloud devops engineer",
    "cloud engineer",
    "cloud architect",
    "cloud software developer",
    "database administrator",
    "database designer",
    "database developer",
    "database integrator",
    "data engineer",
    "data scientist",
    "data analyst",
    "data warehouse designer",
    "blockchain developer",
    "blockchain architect",
    "embedded system designer",
    "embedded systems software developer",
    "embedded systems security engineer",
    "artificial intelligence engineer",
    "computer scientist",
    "computer hardware engineer",
    "computer vision engineer",
    "bioinformatics scientist",
    "software architect",
    "software developer",
    "software tester",
    "software analyst",
    "user interface developer",
    "user experience analyst",
    "telecommunications engineer",
    "telecommunications analyst",
    "network administrator",
    "network architect",
    "network engineer",
    "system administrator",
    "system architect",
    "system developer",
    "system analyst",
    "system tester",
    "test analyst",
    "integration tester",
    "qa engineer",
    "security administrator",
    "cybersecurity",
    "iot developer",
]

# Lọc nghề IT

In [13]:
import re

pattern = "|".join(re.escape(x) for x in it_patterns)

esco_it_refined = esco_rel[
    esco_rel["occupationLabel"].str.lower().str.contains(pattern, na=False)
].copy()

print("ESCO IT refined:", esco_it_refined.shape)
sorted(esco_it_refined["occupationLabel"].dropna().unique())[:200]

ESCO IT refined: (5581, 6)

['ICT accessibility tester',
 'ICT account manager',
 'ICT application configurator',
 'ICT application developer',
 'ICT auditor manager',
 'ICT business analysis manager',
 'ICT business analyst',
 'ICT business development manager',
 'ICT buyer',
 'ICT capacity planner',
 'ICT change and configuration manager',
 'ICT consultant',
 'ICT disaster recovery analyst',
 'ICT documentation manager',
 'ICT environmental manager',
 'ICT help desk agent',
 'ICT help desk manager',
 'ICT information and knowledge manager',
 'ICT integration tester',
 'ICT network administrator',
 'ICT network architect',
 'ICT network engineer',
 'ICT network technician',
 'ICT operations manager',
 'ICT presales engineer',
 'ICT product manager',
 'ICT project manager',
 'ICT quality assurance manager',
 'ICT research consultant',
 'ICT research manager',
 'ICT resilience manager',
 'ICT security administrator',
 'ICT security technician',
 'ICT system administrator',
 'ICT system analyst',
 'ICT system architect',
 'ICT system developer',
 'ICT system integration consultant',
 'ICT system tester',
 'ICT teacher secondary school',
 'ICT technician',
 'ICT test analyst',
 'ICT trainer',
 'ICT usability tester',
 'ICT vendor relationship manager',
 'IoT developer',
 'artificial intelligence engineer',
 'bioinformatics scientist',
 'blockchain architect',
 'blockchain developer',
 'chief ICT security officer',
 'cloud DevOps engineer',
 'cloud architect',
 'cloud engineer',
 'cloud software developer',
 'computer games, multimedia and software specialised seller',
 'computer hardware engineer',
 'computer hardware engineering technician',
 'computer scientist',
 'computer software and multimedia shop manager',
 'computer vision engineer',
 'computers, computer peripheral equipment and software distribution manager',
 'cybersecurity risk manager',
 'data analyst',
 'data engineer',
 'data scientist',
 'data warehouse designer',
 'database administrator',
 'database designer',
 'database developer',
 'database integrator',
 'embedded system designer',
 'embedded systems security engineer',
 'embedded systems software developer',
 'green ICT consultant',
 'import export manager in computers, computer peripheral equipment and software',
 'import export specialist in computers, peripheral equipment and software',
 'industrial mobile devices software developer',
 'mobile application developer',
 'social security administrator',
 'software analyst',
 'software architect',
 'software developer',
 'software manager',
 'software tester',
 'telecommunications analyst',
 'telecommunications engineer',
 'telecommunications engineering technician',
 'user experience analyst',
 'user interface developer',
 'web designer',
 'web developer',
 'webmaster',
 'wholesale merchant in computer peripheral equipment and software']

# Nhóm essential skills - BẮT BUỘC CÓ

In [14]:
essential_df = (
    esco_it_refined[esco_it_refined["relationType"].str.lower() == "essential"]
    .groupby(["occupationUri", "occupationLabel"])["skillLabel"]
    .apply(lambda x: sorted(set(x.dropna())))
    .reset_index(name="essential_skills")
)

# Nhóm optional skills - KHÔNG BẮT BUỘC

In [15]:
optional_df = (
    esco_it_refined[esco_it_refined["relationType"].str.lower() == "optional"]
    .groupby(["occupationUri", "occupationLabel"])["skillLabel"]
    .apply(lambda x: sorted(set(x.dropna())))
    .reset_index(name="optional_skills")
)

# Gộp lại

In [16]:
esco_it_taxonomy = essential_df.merge(
    optional_df,
    on=["occupationUri", "occupationLabel"],
    how="outer"
)
esco_it_taxonomy.sample(10, random_state=42)

esco_it_taxonomy.head()

,occupationUri,occupationLabel,essential_skills,optional_skills
0,http://data.europa.eu/esco/occupation/02eb0ae6...,telecommunications engineer,"[ICT communications protocols, ICT network rou...","[ABAP, AJAX, APL, ASP.NET, Agile project manag..."
1,http://data.europa.eu/esco/occupation/0464b062...,ICT security administrator,"[ICT network security risks, ICT safety, Inter...","[ICT encryption, ICT infrastructure, ICT secur..."
2,http://data.europa.eu/esco/occupation/04ba4d6c...,software analyst,"[ICT system user requirements, analyse busines...","[ABAP, AJAX, APL, ASP.NET, Agile development, ..."
3,http://data.europa.eu/esco/occupation/0ab5c12c...,ICT test analyst,"[address problems critically, develop ICT test...","[Agile project management, ICT debugging tools..."
4,http://data.europa.eu/esco/occupation/0d595b87...,ICT teacher secondary school,"[ICT hardware specifications, ICT software spe...","[ICT communications protocols, adolescent soci..."

# Xem vài nghề mẫu

In [17]:
esco_it_taxonomy.sample(10, random_state=42)

,occupationUri,occupationLabel,essential_skills,optional_skills
40,http://data.europa.eu/esco/occupation/68d973df...,bioinformatics scientist,"[analyse scientific data, apply for research f...","[apply blended learning, biometrics, computer ..."
22,http://data.europa.eu/esco/occupation/349ee6f6...,cloud engineer,"[ICT system integration, ICT system programmin...","[ICT security standards, Java (computer progra..."
55,http://data.europa.eu/esco/occupation/8b6388a4...,ICT project manager,"[ICT project management, ICT project managemen...","[Agile development, Agile project management, ..."
72,http://data.europa.eu/esco/occupation/bb95ef58...,ICT buyer,"[adhere to organisational guidelines, analyse ...","[ICT market, business ICT systems, business re..."
0,http://data.europa.eu/esco/occupation/02eb0ae6...,telecommunications engineer,"[ICT communications protocols, ICT network rou...","[ABAP, AJAX, APL, ASP.NET, Agile project manag..."
26,http://data.europa.eu/esco/occupation/3b1ea27c...,ICT change and configuration manager,"[DevOps, ICT process quality models, ICT proje...","[Apache Maven, Chef (tools for software config..."
39,http://data.europa.eu/esco/occupation/64c7d461...,ICT network technician,"[ICT network cable limitations, ICT network ro...","[Apache Tomcat, Cisco, ICT communications prot..."
67,http://data.europa.eu/esco/occupation/a99b38bc...,ICT resilience manager,"[ICT recovery techniques, analyse business pro...","[ICT network security risks, ICT process quali..."
10,http://data.europa.eu/esco/occupation/16605833...,ICT presales engineer,"[ICT sales methodologies, apply conflict manag...","[ICT market, ICT system user requirements, SAS..."
44,http://data.europa.eu/esco/occupation/731f38f1...,ICT integration tester,"[address problems critically, execute integrat...","[Agile project management, ICT debugging tools..."

# Kết quả thu được

- nghề IT

- skill bắt buộc

- skill không bắt buộc